# Generated by Django 5.0.6 on 2024-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
