# Generated by Django 5.0.6 on 2024-12-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_application_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
