# Generated by Django 5.0.6 on 2024-12-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_application_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
