# Generated by Django 5.0.6 on 2024-11-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('coach', 'Coach'), ('assistant coach', 'Assistant Coach')], default='other', max_length=20),
        ),
    ]
