# Generated by Django 5.0.6 on 2024-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women')], max_length=10, null=True),
        ),
    ]
