# Generated by Django 5.0.6 on 2024-11-23 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_equipment_sport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.IntegerField()),
                ('equipment_id', models.IntegerField()),
                ('equipment_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
