# Generated by Django 5.0.6 on 2024-11-23 03:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_borrowrequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='request_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
