# Generated by Django 5.0.6 on 2024-11-27 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_event_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='myapp.event'),
        ),
    ]
