# Generated by Django 5.0.6 on 2024-11-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_category_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
