# Generated by Django 5.0.6 on 2024-11-27 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='myapp.category'),
        ),
    ]
